CREATE TABLE IF NOT EXISTS "django_migrations" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" datetime NOT NULL);
CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE IF NOT EXISTS "django_content_type" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app_label" varchar(100) NOT NULL, "model" varchar(100) NOT NULL);
CREATE UNIQUE INDEX "django_content_type_app_label_model_76bd3d3b_uniq" ON "django_content_type" ("app_label", "model");
CREATE TABLE IF NOT EXISTS "auth_group_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" ON "auth_group_permissions" ("group_id", "permission_id");
CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" ("group_id");
CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" ("permission_id");
CREATE TABLE IF NOT EXISTS "auth_permission" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "content_type_id" integer NOT NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "codename" varchar(100) NOT NULL, "name" varchar(255) NOT NULL);
CREATE UNIQUE INDEX "auth_permission_content_type_id_codename_01ab375a_uniq" ON "auth_permission" ("content_type_id", "codename");
CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "auth_permission" ("content_type_id");
CREATE TABLE IF NOT EXISTS "auth_group" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(150) NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS "chats_user" ("password" varchar(128) NOT NULL, "last_login" datetime NULL, "is_superuser" bool NOT NULL, "user_id" char(32) NOT NULL PRIMARY KEY, "username" varchar(150) NOT NULL UNIQUE, "email" varchar(255) NOT NULL UNIQUE, "first_name" varchar(150) NOT NULL, "last_name" varchar(150) NOT NULL, "phone_number" varchar(15) NOT NULL, "date_joined" datetime NOT NULL, "is_active" bool NOT NULL, "is_staff" bool NOT NULL);
CREATE TABLE IF NOT EXISTS "chats_user_groups" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" char(32) NOT NULL REFERENCES "chats_user" ("user_id") DEFERRABLE INITIALLY DEFERRED, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "chats_user_user_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" char(32) NOT NULL REFERENCES "chats_user" ("user_id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "chats_conversation" ("conversation_id" char(32) NOT NULL PRIMARY KEY, "name" varchar(255) NULL, "created_at" datetime NOT NULL);
CREATE TABLE IF NOT EXISTS "chats_conversation_participants" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "conversation_id" char(32) NOT NULL REFERENCES "chats_conversation" ("conversation_id") DEFERRABLE INITIALLY DEFERRED, "user_id" char(32) NOT NULL REFERENCES "chats_user" ("user_id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "chats_message" ("message_id" char(32) NOT NULL PRIMARY KEY, "message_body" text NOT NULL, "sent_at" datetime NOT NULL, "conversation_id" char(32) NOT NULL REFERENCES "chats_conversation" ("conversation_id") DEFERRABLE INITIALLY DEFERRED, "sender_id" char(32) NOT NULL REFERENCES "chats_user" ("user_id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX "chats_user_groups_user_id_group_id_09c179f1_uniq" ON "chats_user_groups" ("user_id", "group_id");
CREATE INDEX "chats_user_groups_user_id_f3f94763" ON "chats_user_groups" ("user_id");
CREATE INDEX "chats_user_groups_group_id_374521e3" ON "chats_user_groups" ("group_id");
CREATE UNIQUE INDEX "chats_user_user_permissions_user_id_permission_id_0eb4ff7c_uniq" ON "chats_user_user_permissions" ("user_id", "permission_id");
CREATE INDEX "chats_user_user_permissions_user_id_dad946f6" ON "chats_user_user_permissions" ("user_id");
CREATE INDEX "chats_user_user_permissions_permission_id_88fa3e6b" ON "chats_user_user_permissions" ("permission_id");
CREATE UNIQUE INDEX "chats_conversation_participants_conversation_id_user_id_d9eb2230_uniq" ON "chats_conversation_participants" ("conversation_id", "user_id");
CREATE INDEX "chats_conversation_participants_conversation_id_8378f6a9" ON "chats_conversation_participants" ("conversation_id");
CREATE INDEX "chats_conversation_participants_user_id_23f59f7f" ON "chats_conversation_participants" ("user_id");
CREATE INDEX "chats_message_conversation_id_91ecdd5c" ON "chats_message" ("conversation_id");
CREATE INDEX "chats_message_sender_id_4f3659eb" ON "chats_message" ("sender_id");
CREATE TABLE IF NOT EXISTS "django_admin_log" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "object_id" text NULL, "object_repr" varchar(200) NOT NULL, "action_flag" smallint unsigned NOT NULL CHECK ("action_flag" >= 0), "change_message" text NOT NULL, "content_type_id" integer NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" char(32) NOT NULL REFERENCES "chats_user" ("user_id") DEFERRABLE INITIALLY DEFERRED, "action_time" datetime NOT NULL);
CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "django_admin_log" ("content_type_id");
CREATE INDEX "django_admin_log_user_id_c564eba6" ON "django_admin_log" ("user_id");
CREATE TABLE IF NOT EXISTS "authtoken_token" ("key" varchar(40) NOT NULL PRIMARY KEY, "created" datetime NOT NULL, "user_id" char(32) NOT NULL UNIQUE REFERENCES "chats_user" ("user_id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "django_session" ("session_key" varchar(40) NOT NULL PRIMARY KEY, "session_data" text NOT NULL, "expire_date" datetime NOT NULL);
CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" ("expire_date");